# Generated by Django 2.2.17 on 2021-01-28 04:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color_text', models.CharField(choices=[('w', 'white'), ('b', 'black')], default='b', max_length=1)),
                ('color_background', colorfield.fields.ColorField(default='#A5F8CE', max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='block-image/header')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='block-image/thumbnail')),
                ('resume', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='post.Category')),
            ],
        ),
    ]
