# Generated by Django 2.2.17 on 2021-01-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color_text', models.CharField(choices=[('w', 'white'), ('b', 'black')], default='w', max_length=1)),
                ('color_background', models.CharField(default='#A5F8CE', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='TypeImage',
        ),
        migrations.DeleteModel(
            name='TypeText',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='block-image/header'),
        ),
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='block-image/thumbnail'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
