# Generated by Django 2.2.17 on 2021-01-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210128_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color_text',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black')], default='b', max_length=1),
        ),
    ]
