# Generated by Django 2.2.17 on 2021-01-28 03:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210128_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color_background',
            field=colorfield.fields.ColorField(default='#A5F8CE', max_length=18),
        ),
    ]
