# Generated by Django 2.2.17 on 2021-01-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210129_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='header/%Y/%m/'),
        ),
    ]
